### PR TITLE
change to be compatible with 1.0+

### PR DESCRIPTION
**Pull request by rohan-varma**
I was getting the following error: 

"ValueError: Variable d_wconv1/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?"

I changed the variable_scope to have reuse = False to fix it.

### CODE REVIEW

**Comment by adeshpande3** [comment]
So, like we talked about yesterday, iPython notebooks and Tensorflow graphs get problematic and sometimes it's tough to determine the reuse option's value.

I think this change should be fine, but I'm still not 100% on scope and reuse in Tensorflow. Maybe just restart kernel and run everything again, and then see the results of both versions (with reuse=False and with reuse=None)

**Comment by nealmcb** [comment]
I'm very new to all this, but I ran into the same error. I tried this pull request, but still got the same error. I tried TensorFlow 1.2 and 1.0, and I tried using both None and False.

I also wrote this up as an issue (before finding this): #5

**Comment by houssamzenati** [comment]
Hi I also have same problem
 ValueError: Variable d_wconv1/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

I use python 3.6, latest version of tensorflow. 

Is there a way to fix it?

**Comment by rohan-varma** [comment]
@nealmcb @houssamzenati sorry for the late response, but I've just merged this and it should be fixed now. Thanks for the reminder!

**Comment by CharlesNord** [comment]
Hi, my tensorflow version is 1.3.0, the problem still exists

**Comment by rohan-varma** [comment]
Yeah, I've noticed this problem as well. Interestingly, it seems to be only for `AdamOptimizer` and not `GradientDescentOptimizer`, which is interesting. I've opened up an issue with the main tensorflow repo here: https://github.com/tensorflow/tensorflow/issues/13887

**Comment by rohan-varma** [comment]
@CharlesNord https://github.com/uclaacmai/Generative-Adversarial-Network-Tutorial/pull/7 should fix this! Going to merge it soon. (Edit: merged it. See https://github.com/tensorflow/tensorflow/issues/13887 for details)

**Pull request merged**
